### ISSUE TITLE
clist: rewrite code and take out WaitGroup state linked code

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tmlibs#112]
Inspired by undeterministic crash from this bug https://github.com/tendermint/tendermint/issues/985, the mere presence of that bug shows that our code has some underlying problems that perhaps might get triggered later on by increases in concurrency or some weird state.

I noticed that in the code we have a bunch of comments that seem to convey that allowing "races" is ok:
https://github.com/tendermint/tmlibs/blob/e3bffd8fbd9427fbfe0413ad9c813fe8b702f71f/clist/clist.go#L99

https://github.com/tendermint/tmlibs/blob/e3bffd8fbd9427fbfe0413ad9c813fe8b702f71f/clist/clist.go#L115

plus I see a bunch of logic in there where we do `*sync.WaitGroup.Add(1)` expecting `*sync.WaitGroup.Done()` and `*sync.WaitGroup.Wait()` to correspondingly be invoked. In these cases we are directly playing with racy behavior and the reported bug is a manifestation.

I'd suggest let's rewrite clist with simpler and easily reasoned about concurrency protections i.e. just mutexes.

**Comment by paralin** [comment]
Thanks for this. I run into this pretty frequently now, actually.

**Comment by jaekwon** [comment]
We still need to use WaitGroups given what CList is trying to achieve, which is the ability concurrently navigate the linked list (next/prev).  But yes, it's possible to use add a mutex to CElement and to remove usage of atomic.*.  The problem is that the WaitGroup is being re-used, so what we need to do is replace the WaitGroup with `waitGroup1()` (a new WaitGroup with 1 added), under protection of CElement.mtx.

**Comment by jaekwon** [comment]
See the above fix.

We can't avoid using WaitGroups or for-loops given the documentation spec without re-implementing the primitives that already exist in golang/sync.  Notice that WaitGroup allows many go-routines to be simultaneously released, which is what we want.  Mutex doesn't do this.  RWMutex does this, but it's clumsy to use in the way that a WaitGroup would be used -- and we'd end up having two RWMutex's for prev/next each, which is doubly confusing.

sync.Cond would be sort-of useful, but we don't need a write-lock in the for-loop.  Use sync.Cond when you need serial access to the "condition".  In our case our condition is `if next != nil || removed`, and there's no reason to serialize that condition for people who want NextWait() (since it's just a read-only operation).
