### ISSUE TITLE
WIP: Deterministic Time

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tmlibs#120]
# Objective

Create a more or less drop/replace alternative to time that helps create deterministic programs for testing and perhaps even execution.

# TODO

- [ ] search/comparison of alternative libs
- [x] [NewRepeatTimerWithTickerMaker()](https://github.com/tendermint/tmlibs/blob/sdk2/common/repeat_timer.go)
- [ ] NewClock()

**Comment by jaekwon** [comment]
```golang
func myRoutine() {
    for {
        switch value {
        case 0:
        case 1:
            time.Sleep(time.Millisecond)
        case 2:
            mtx.Lock()
            mtx.Unlock()
        case 3:
            blockingCh <- struct{}{}
        }
        ... // mutate switch-value
    }
}
```

The problem is that we cannot hook into all the places where we could possibly block.  Do we need to?  Well, we need to MockClock that everything has run to "completion", e.g. everyone is blocking on something.  There's no good general way to do this... searching for alternative solutions.

**Comment by jaekwon** [comment]
apparently you can [capture the stack trace of all goroutines](https://stackoverflow.com/questions/19094099/how-to-dump-goroutine-stacktraces) with `pprof.Lookup("goroutine").WriteTo(os.Stdout, 1)`.  That seems relevant.

**Comment by jaekwon** [comment]
Or better, `runtime.Stack(buf []byte, all bool) int`, notice the "all".  Stack formats a stack trace of the calling goroutine into buf and returns the number of bytes written to buf. If all is true, Stack formats stack traces of all other goroutines into buf after the trace for the current goroutine.

**Comment by jaekwon** [comment]
```golang
package main

import (
	"fmt"
	"runtime"
	"sync"
	"time"
)

func main() {
	go blockSleep()
	go blockChan()
	go blockMutex()
	go blockWaitGroup()

	fmt.Println("Booting blocking goroutines...")
	time.Sleep(time.Second * 3)
	capture()

	fmt.Println("\n\n\nBooting notblocking goroutines...")
	go notblockSleep()
	go notblockChan()
	go notblockMutex()
	go notblockWaitGroup()

	time.Sleep(time.Second * 3)
	capture()
}

func blockSleep() {
	time.Sleep(99999999 * time.Second)
}

func blockChan() {
	foo := make(chan struct{})
	foo <- struct{}{}
}

func blockMutex() {
	mtx := new(sync.Mutex)
	mtx.Lock()
	mtx.Lock()
}

func blockWaitGroup() {
	var wg sync.WaitGroup
	wg.Add(1)
	wg.Wait()
}

// line 41

func notblockSleep() {
	for {
		time.Sleep(0 * time.Second)
	}
}

func notblockChan() {
	foo := make(chan struct{})
	for {
		select {
		case foo <- struct{}{}:
		default:
		}
	}
}

func notblockMutex() {
	mtx := new(sync.Mutex)
	for {
		mtx.Lock()
		mtx.Unlock()
	}
}

func notblockWaitGroup() {
	var wg sync.WaitGroup
	for {
		wg.Wait()
	}
}

func capture() {
	trace := make([]byte, 102400)
	count := runtime.Stack(trace, true)
	fmt.Printf("Stack of %d bytes: %s\n", count, trace)
}
```


```
$ go run foo.go
Booting blocking goroutines...
Stack of 1545 bytes: goroutine 1 [running]:
main.capture()
	/example/foo.go:86 +0x87
main.main()
	/example/foo.go:18 +0xde

goroutine 5 [sleep]:
time.Sleep(0x163457821ef3600)
	/go/1.9./libexec/src/runtime/time.go:65 +0x130
main.blockSleep()
	/example/foo.go:31 +0x30
created by main.main
	/example/foo.go:11 +0x39

goroutine 6 [chan send]:
main.blockChan()
	/example/foo.go:36 +0x4e
created by main.main
	/example/foo.go:12 +0x51

goroutine 7 [semacquire]:
sync.runtime_SemacquireMutex(0xc420084004, 0x0)
	/go/1.9./libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420084000)
	/go/1.9./libexec/src/sync/mutex.go:134 +0xee
main.blockMutex()
	/example/foo.go:42 +0x4e
created by main.main
	/example/foo.go:13 +0x69

goroutine 8 [semacquire]:
sync.runtime_Semacquire(0xc42001208c)
	/go/1.9./libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420012080)
	/go/1.9./libexec/src/sync/waitgroup.go:131 +0x72
main.blockWaitGroup()
	/example/foo.go:48 +0x57
created by main.main
	/example/foo.go:14 +0x81




Booting notblocking goroutines...
Stack of 2687 bytes: goroutine 1 [running]:
main.capture()
	/example/foo.go:86 +0x87
main.main()
	/example/foo.go:27 +0x19b

goroutine 5 [sleep]:
time.Sleep(0x163457821ef3600)
	/go/1.9./libexec/src/runtime/time.go:65 +0x130
main.blockSleep()
	/example/foo.go:31 +0x30
created by main.main
	/example/foo.go:11 +0x39

goroutine 6 [chan send]:
main.blockChan()
	/example/foo.go:36 +0x4e
created by main.main
	/example/foo.go:12 +0x51

goroutine 7 [semacquire]:
sync.runtime_SemacquireMutex(0xc420084004, 0x0)
	/go/1.9./libexec/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420084000)
	/go/1.9./libexec/src/sync/mutex.go:134 +0xee
main.blockMutex()
	/example/foo.go:42 +0x4e
created by main.main
	/example/foo.go:13 +0x69

goroutine 8 [semacquire]:
sync.runtime_Semacquire(0xc42001208c)
	/go/1.9./libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420012080)
	/go/1.9./libexec/src/sync/waitgroup.go:131 +0x72
main.blockWaitGroup()
	/example/foo.go:48 +0x57
created by main.main
	/example/foo.go:14 +0x81

goroutine 33 [runnable]:
time.Sleep(0x0)
	/go/1.9./libexec/src/runtime/time.go:49 +0x1ef
main.notblockSleep()
	/example/foo.go:55 +0x2a
created by main.main
	/example/foo.go:21 +0x140

goroutine 34 [runnable]:
main.notblockChan()
	/example/foo.go:63 +0x5a
created by main.main
	/example/foo.go:22 +0x158

goroutine 35 [runnable]:
sync.(*Mutex).Unlock(0xc420084008)
	/go/1.9./libexec/src/sync/mutex.go:175 +0xc8
main.notblockMutex()
	/example/foo.go:73 +0x4e
created by main.main
	/example/foo.go:23 +0x170

goroutine 36 [runnable]:
sync.(*WaitGroup).Wait(0xc4200b6020)
	/go/1.9./libexec/src/sync/waitgroup.go:104 +0xc2
main.notblockWaitGroup()
	/example/foo.go:80 +0x40
created by main.main
	/example/foo.go:24 +0x188
```

Can someone create a thing that can try the above many many times (1M times) and see if it's deterministically capable of labeling goroutines as blocked or not?

**Comment by spacejam** [comment]
an approach like this may lead to a zero-code modification deterministic execution harness (needs to pin a little more info about the runtime when choosing the next thread to actually be deterministic but the idea is sound): https://github.com/spacejam/crack/blob/master/determined/determined.py#L37

**Comment by jaekwon** [comment]
That works in python but not in golang....
Wait, I think there may be ways to hack into goroutines via cgo.
But if the above works, I think it implies that runtime.Stack() is precise (e.g. status is always runnable as long as it isn't blocked in any way), which probably means we can use it for our testing purposes.  If we use Python we might need that approach.  Maybe Python has something similar to runtime.Stack() as well?

**Comment by spacejam** [comment]
@jaekwon while the script is written in Python, the example usage is against a go binary

**Comment by spacejam** [comment]
Basically, it uses gdb as easy mode ptrace + symbol lookup to control deterministic execution. I just added the go runtime sleep and mutex symbols as an illustration but this would be expanded to include channel operations and spawning of goroutines as well in actual usage

**Comment by spacejam** [comment]
What's the actual goal of determinism here? 

If we are trying to search-and-destroy flaky tests before release, (with some improvements) the above gdb script approach can be pursued with different seeds to yield different deterministic executions until the test flakes, and it can then be deterministically from then on out to fix the bug quickly. 

If the goal is to have less bugs, a deterministic time source does not necessarily address this. Just because you run buggy code in the same sequence, doesn't make it less buggy. Tests will be more deterministic, but the tests also will not execute as many execution interleavings across runs, and more bugs will go undiscovered. 

A flaky test can be better than a deterministic test with less coverage over time, because it will sometimes tell you that there's a bug. In some of my projects I use non-deterministically seeded quickcheck all the time to find bugs, but then give it specific failing cases when I identify a bug, which I find yields a nice mix of determinism for regressions and non-determinism for coverage. Knowing (of the existence of bugs) is half the battle :)

To have less bugs, you have to address sources of divergence between the minds of engineers / model checkers and the production execution interleaving space. Constraining the interleaving space so that it can be reasoned about by a) engineers and b) machines, is how you achieve this, because making humans or formal verification systems orders of magnitude more powerful is generally cost-prohibitive.

So, how do you constain the space of possible interleavings so that good engineers or verification tools can reason about what the code might actually do when running in production, without costing millions or billions to engineer better human minds or quantum-leap improvements in verification?

Thought experiment: how would you catch this bug? (from below linked MCR paper)
![mcr figure 2](https://user-images.githubusercontent.com/1505488/34779301-19aaec9a-f620-11e7-8948-fd428822fb3d.png)

Every additional thread/goroutine running identical code on shared state adds an exponent to the analysis complexity. So, option 1 is to constrain the usage of shared state. Note that *this does not mean avoid using threads*! 

One example of using threads, but still doing interesting things with shared state, is by using an existing tool for handling "confusing concurrency issues" like STM or an in-memory transactional database. STM and databases have solved this problems fairly comprehensively. I'm not sure what the current state of STM in golang is, but this might not be the hardest thing to implement in the limited cases we care about.

If we're not going to trust a pre-existing well-tested implementation of concurrent state management, we are going to have lots of bugs that are extremely hard to reason about, even by the strong engineers working on this system. We could [build something](https://parasol.tamu.edu/~jeff/academic/mcr.pdf) that infers specific interesting relationships and explores relevant execution interleavings based on them. This will take engineer months and would be really cool, and probably very interesting for engineers all over the place if you wanted to open source it. But it doesn't fix the issue of bugs being created due to the human mind's limitations on reasoning about trillions of execution interleavings.

Recommendation: keep most of the architecture, manage shared state with STM, when a test is flaky use something like gdb to constrain execution interleavings and get a deterministic execution seed. Build constrained STM if golang doesn't have a great solution yet.

**Comment by spacejam** [comment]
I feel like the main benefit of deterministic clocks is the ability to create a regression test without relying on running the code in a weird gdb harness. But, that will involve threading through every piece of nondeterminism, of which there is plenty in the codebase. It is a good idea to be clear about specific pain points and what they are worth to solve in the short, medium, and long terms.

Threading determinism all the way into a system that was not built for it is possible, but effort-intensive. I think doing something that constrains concurrent mutation across multiple objects like STM or more higher-level locks across objects that have coupled linearization requirements, plus some tooling that makes flakes less painful to fix may be a lot less effort while improving the overall engineering experience.

**Comment by jaekwon** [comment]
> Basically, it uses gdb as easy mode ptrace + symbol lookup to control deterministic execution. I just added the go runtime sleep and mutex symbols as an illustration but this would be expanded to include channel operations and spawning of goroutines as well in actual usage

Ok, but we'd be assuming all kinds of things, like that the Go runtime doesn't in the background use those symbols.  If [runtime.Stack](https://github.com/tendermint/tmlibs/issues/120#issuecomment-355153796) is doing what I think it's doing, then it's clearly the better alternative since it would be telling us precisely the status of each goroutine.

> If the goal is to have less bugs, a deterministic time source does not necessarily address this. Just because you run buggy code in the same sequence, doesn't make it less buggy. Tests will be more deterministic, but the tests also will not execute as many execution interleavings across runs, and more bugs will go undiscovered.

That's not the goal.  The goal is to be able to reproduce a bug when we see it.  It's the difference between picking up a bug that's frozen on the ground, and one that's flying about.  It's easier to squash the one that's immobile.

> Thought experiment: how would you catch this bug? (from below linked MCR paper)

I'd catch it with the race detector.

> STM

You'll need to provide a concrete example, given a specific concern in the codebase, and write an analysis of the existing working model, and the solution using STM, and do a pro/con analysis to make a convincing argument.  

The objective is to make time deterministic, so that we can test for processes that require the usage of time, like tickers.  The point of making it deterministic is to make bugs reproducible, so that they are easier to fix once found.  I don't see how STM has anything to do with that.

> But, that will involve threading through every piece of nondeterminism, of which there is plenty in the codebase.

We don't need to remove all non-determinism to benefit from deterministic clocks when testing pieces in isolation, using the reflect.Stack approach.

**Comment by spacejam** [comment]
@jaekwon zero code solution: rr's chaos mode (`rr record -h`) is well-suited for this, being specifically written to provide deterministic replay. No need to spend energy reinventing the wheel on this one.

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1881
